plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "vendor/**/*"
  NewCops: disable
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 102

Naming/FileName:
  Exclude:
    - "gemfiles/*"
    - "lib/carrierwave-aws.rb"
    - "spec/carrierwave-aws_spec.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/SpecFilePathFormat:
  Enabled: false

# Documentation is coming
Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Gemfile*"
    - "Rakefile"
    - "*.gemspec"
    - "gemfiles/*"
    - "spec/**/*"

Style/IfUnlessModifier:
  Enabled: false

# Extend self preserves private methods
Style/ModuleFunction:
  Enabled: false
