AllCops:
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "vendor/**/*"
  NewCops: disable
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Naming/FileName:
  Exclude:
    - "gemfiles/*"
    - "lib/carrierwave-aws.rb"
    - "spec/carrierwave-aws_spec.rb"

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Gemfile*"
    - "Rakefile"
    - "*.gemspec"
    - "spec/**/*"

Style/IfUnlessModifier:
  Enabled: false

# Documentation is coming
Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

# Extend self preserves private methods
Style/ModuleFunction:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': "[]"
    '%W': "[]"
